#include "illegal_exception.hpp"

using namespace std;

const char* illegal_exception::invalid_bound() { return "illegal argument"; }